apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tasks-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
      - image: hossambarakat/tasklist
        imagePullPolicy: IfNotPresent
        name:  tasks-app
        ports:
        - containerPort:  80
          name: tasks-app